<?php

namespace App\Services\AI;

use App\Models\File;
use App\Models\Transcription;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Auth;

class TranscriptionService
{
    /**
     * Transcribe an audio file using a mock AI.
     */
    public function transcribe(UploadedFile $uploadedFile): Transcription
    {
        // 1. Store the audio file first
        $originalName = $uploadedFile->getClientOriginalName();
        $extension = $uploadedFile->getClientOriginalExtension();
        $mimeType = $uploadedFile->getMimeType() ?? 'audio/mpeg';
        $size = $uploadedFile->getSize();
        
        $storedName = time() . '_' . uniqid() . '.' . $extension;
        
        $path = $uploadedFile->storeAs("uploads/audio", $storedName, 'private');

        $fileModel = File::create([
            'user_id' => Auth::id(),
            'tool_type' => 'audio_to_text',
            'original_name' => $originalName,
            'stored_name' => $storedName,
            'mime_type' => $mimeType,
            'extension' => $extension,
            'size' => $size,
            'storage_path' => $path,
            'status' => 'processing',
        ]);

        // 2. Mock AI Processing
        sleep(2);

        $mockTranscript = "This is a mocked transcription of the uploaded audio file '{$originalName}'.\n\n"
                        . "In a real-world scenario, this text would be generated by an AI service like OpenAI Whisper, AssemblyAI, or Google Cloud Speech-to-Text API.\n"
                        . "The audio duration and language would also be automatically detected.";

        // 3. Save Transcription Result
        $transcription = Transcription::create([
            'user_id' => Auth::id(),
            'file_id' => $fileModel->id,
            'language' => 'en',
            'duration_seconds' => random_int(30, 300), // mock duration
            'transcript' => $mockTranscript,
        ]);

        $fileModel->status = 'completed';
        $fileModel->save();

        return $transcription;
    }
}
